Repository appuio/component-openshift4-slos, pull requests merged in 2022-09, with the labels that each got.

#12 Add Kubernetes API server SLOs
  class/defaults.yml
  component/blackbox-exporter.libsonnet
  component/main.jsonnet
  component/slos.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/runbooks/kubernetes_api.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_configmap.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_deploy.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_probes.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/kubernetes_api.yaml
Labels: enhancement

#20 Prefix all SLO alertnames and add an `slo: true` label
  class/defaults.yml
  component/slos.libsonnet
  docs/modules/ROOT/pages/runbooks/kubernetes_api.adoc
  tests/golden/defaults/openshift4-slos/openshift4-slos/appuio-ch-http-get-availability.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/ingress.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/kubernetes_api.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/storage.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/workload-schedulability.yaml
Labels: change

#21 Fix wrong indentation in blackbox exporter config
  component/blackbox-exporter.libsonnet
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_configmap.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_deploy.yaml
Labels: bug

#16 Update dependency docker.io/curlimages/curl to v7.85.0
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/30_canaryImageStream.yaml
Labels: dependency

#19 Add network SLO
  class/defaults.yml
  component/main.jsonnet
  component/network-canary.libsonnet
  component/slos.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/runbooks/network.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/defaults/openshift4-slos/openshift4-slos/10_network_canary_namespace.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_network_canary_daemonset.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_network_canary_service.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_network_canary_servicemonitor.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/network.yaml
Labels: enhancement
