Repository appuio/component-openshift4-slos, pull requests merged in 2022-08, with the labels that each got.

#1 Initial implementation: Generate PrometheusRules using Sloth
  .gitignore
  .sync.yml
  class/defaults.yml
  class/openshift4-slos.yml
  component/main.jsonnet
  component/sloth-input.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  run-sloth
  tests/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/getting-started.yaml
Labels: enhancement

#3 Add Blackbox Exporter for use with SLOs
  class/defaults.yml
  component/blackbox-exporter.libsonnet
  component/main.jsonnet
  component/sloth-input.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/00_namespace.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/10_blackbox_exporter_sa.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_configmap.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_deploy.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_service.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_probes.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/appuio-ch-http-get-availability.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/getting-started.yaml
Labels: enhancement

#5 Add option to define common alert labels and to disable SLOs
  class/defaults.yml
  component/main.jsonnet
  component/slos.libsonnet
  component/sloth-input.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/appuio-ch-http-get-availability.yaml
Labels: enhancement

#6 Add SLO for Storage Operations
  class/defaults.yml
  component/slos.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/runbooks/storage.adoc
  docs/modules/ROOT/partials/nav.adoc
  docs/modules/ROOT/partials/runbooks/contribution_note.adoc
  tests/golden/defaults/openshift4-slos/openshift4-slos/storage.yaml
Labels: enhancement

#7 Add SLO measuring cluster ingress availability using canary probes
  class/defaults.yml
  component/slos.libsonnet
  docs/modules/ROOT/pages/runbooks/ingress.adoc
  tests/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/ingress.yaml
Labels: enhancement

#9 Add ingress runbook to navigation
  docs/modules/ROOT/partials/nav.adoc
Labels: ignore

#10 Refactor runbooks to put common snippets in partials
  docs/modules/ROOT/pages/runbooks/ingress.adoc
  docs/modules/ROOT/pages/runbooks/storage.adoc
  docs/modules/ROOT/partials/runbooks/alert_types.adoc
  docs/modules/ROOT/partials/runbooks/objective_change_warning.adoc
  docs/modules/ROOT/partials/runbooks/wip_note.adoc
Labels: change

#11 Add scheduler canary controller deployment manifests
  class/defaults.yml
  class/openshift4-slos.yml
  component/scheduler-canary.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  run-kustomize
  tests/golden/defaults/openshift4-slos/scheduler-canary/apiextensions.k8s.io_v1_customresourcedefinition_schedulercanaries.monitoring.appuio.io.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/apps_v1_deployment_scheduler-canary-controller-manager.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/monitoring.coreos.com_v1_servicemonitor_scheduler-canary-controller-manager-metrics-monitor.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/rbac.authorization.k8s.io_v1_clusterrole_scheduler-canary-manager-role.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/rbac.authorization.k8s.io_v1_clusterrole_scheduler-canary-metrics-reader.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/rbac.authorization.k8s.io_v1_clusterrole_scheduler-canary-proxy-role.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/rbac.authorization.k8s.io_v1_clusterrolebinding_scheduler-canary-manager-rolebinding.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/rbac.authorization.k8s.io_v1_clusterrolebinding_scheduler-canary-proxy-rolebinding.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/rbac.authorization.k8s.io_v1_role_scheduler-canary-leader-election-role.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/rbac.authorization.k8s.io_v1_rolebinding_scheduler-canary-leader-election-rolebinding.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/v1_configmap_scheduler-canary-manager-config.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/v1_namespace_appuio-openshift4-slos.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/v1_service_scheduler-canary-controller-manager-metrics-service.yaml
  tests/golden/defaults/openshift4-slos/scheduler-canary/v1_serviceaccount_scheduler-canary-controller-manager.yaml
Labels: enhancement

#8 SLO for Workload Schedulability
  class/defaults.yml
  class/openshift4-slos.yml
  component/main.jsonnet
  component/slos.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/runbooks/workload-schedulability.adoc
  tests/golden/defaults/openshift4-slos/openshift4-slos/30_canary.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/30_canaryImageStream.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/apiextensions.k8s.io_v1_customresourcedefinition_schedulercanaries.monitoring.appuio.io.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/apps_v1_deployment_scheduler-canary-controller-manager.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/monitoring.coreos.com_v1_servicemonitor_scheduler-canary-controller-manager-metrics-monitor.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/rbac.authorization.k8s.io_v1_clusterrole_scheduler-canary-manager-role.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/rbac.authorization.k8s.io_v1_clusterrole_scheduler-canary-metrics-reader.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/rbac.authorization.k8s.io_v1_clusterrole_scheduler-canary-proxy-role.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/rbac.authorization.k8s.io_v1_clusterrolebinding_scheduler-canary-manager-rolebinding.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/rbac.authorization.k8s.io_v1_clusterrolebinding_scheduler-canary-proxy-rolebinding.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/rbac.authorization.k8s.io_v1_role_scheduler-canary-leader-election-role.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/rbac.authorization.k8s.io_v1_rolebinding_scheduler-canary-leader-election-rolebinding.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/v1_configmap_scheduler-canary-manager-config.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/v1_service_scheduler-canary-controller-manager-metrics-service.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/v1_serviceaccount_scheduler-canary-controller-manager.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/workload-schedulability.yaml
Labels: enhancement

#18 Update canary controller to release version
  class/defaults.yml
  component/slos.libsonnet
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/apps_v1_deployment_scheduler-canary-controller-manager.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/workload-schedulability.yaml
Labels: dependency
