Repository appuio/component-openshift4-slos, pull requests merged in 2022-10, with the labels that each got.

#22 Refactor component to use Commodore's Kustomize support
  class/openshift4-slos.yml
  component/scheduler-canary.jsonnet
  run-kustomize
Labels: change

#23 Add explanation page with general tips for improving SLO configurations
  CODEOWNERS
  docs/modules/ROOT/pages/explanations/improving-slos.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#26 Update dependency docker.io/curlimages/curl to v7.86.0
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/30_canaryImageStream.yaml
Labels: dependency
