Repository appuio/component-openshift4-slos, pull requests merged in 2023-02, with the labels that each got.

#34 Update CODEOWNERS to @appuio/aldebaran
  CODEOWNERS
Labels: ignore

#33 Add support for configuring extra Prometheus rules
  component/main.jsonnet
  component/slos.libsonnet
  tests/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/appuio-ch-http-get-availability.yaml
Labels: enhancement

#29 Update dependency docker.io/prom/blackbox-exporter to v0.23.0
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_deploy.yaml
Labels: dependency

#30 Update dependency docker.io/curlimages/curl to v7.87.0
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/30_canaryImageStream.yaml
Labels: dependency

#32 Improve Ingress SLO
  component/slos.libsonnet
  tests/golden/defaults/openshift4-slos/openshift4-slos/ingress.yaml
Labels: enhancement

#35 Update dependency docker.io/curlimages/curl to v7.88.1
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/30_canaryImageStream.yaml
Labels: dependency
