Repository appuio/component-openshift4-slos, pull requests merged in 2024-07, with the labels that each got.

#69 Update docker.io/curlimages/curl Docker tag to v8.8.0
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/30_canaryImageStream.yaml
Labels: dependency

#72 Update quay.io/appuio/scheduler-canary-controller Docker tag to v1.1.0
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/apiextensions.k8s.io_v1_customresourcedefinition_schedulercanaries.monitoring.appuio.io.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/apps_v1_deployment_scheduler-canary-controller-manager.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/rbac.authorization.k8s.io_v1_clusterrole_scheduler-canary-manager-role.yaml
Labels: dependency, bump:minor

#73 Fix CRD sync error caused by big `last-applied-configuration` annotation
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/apiextensions.k8s.io_v1_customresourcedefinition_schedulercanaries.monitoring.appuio.io.yaml
Labels: bug, bump:patch

#75 Update quay.io/appuio/scheduler-canary-controller Docker tag to v1.2.0
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/apps_v1_deployment_scheduler-canary-controller-manager.yaml
Labels: dependency

#74 Implement canary storage SLO
  class/defaults.yml
  component/main.jsonnet
  component/slos.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/runbooks/storage.adoc
  docs/modules/ROOT/pages/runbooks/workload-schedulability.adoc
  tests/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/10_secrets.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/32_storageCanary.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/storage.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/workload-schedulability.yaml
  tests/golden/network-only/openshift4-slos/openshift4-slos/10_secrets.yaml
  tests/network-only.yml
Labels: enhancement, bump:minor
