Repository appuio/component-openshift4-slos, pull requests merged in 2024-04, with the labels that each got.

#64 Treat `distribution=oke` as OpenShift
  component/main.jsonnet
  component/network-canary.libsonnet
  tests/golden/defaults/openshift4-slos/openshift4-slos/00_namespace.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/10_network_canary_namespace.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/appuio-ch-http-get-availability.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/ingress.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/kubernetes_api.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/network.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/storage.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/workload-schedulability.yaml
Labels: enhancement

#65 Allow users to customize the canary pod node affinity
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#67 Add priorityclass system-cluster-critical
  component/blackbox-exporter.libsonnet
  component/network-canary.libsonnet
  component/scheduler-canary.jsonnet
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_deploy.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_network_canary_daemonset.yaml
  tests/golden/defaults/openshift4-slos/openshift4-slos/scheduler-canary-deployment/apps_v1_deployment_scheduler-canary-controller-manager.yaml
  tests/golden/network-only/openshift4-slos/openshift4-slos/20_network_canary_daemonset.yaml
Labels: change

#63 Update docker.io/curlimages/curl Docker tag to v8.7.1
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/30_canaryImageStream.yaml
Labels: dependency

#66 Update docker.io/prom/blackbox-exporter Docker tag to v0.25.0
  class/defaults.yml
  tests/golden/defaults/openshift4-slos/openshift4-slos/20_blackbox_exporter_deploy.yaml
Labels: dependency
